services:
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9411/actuator/health"]
    interval: 30s
    timeout: 10s
    retries: 3
    environment:
      - STORAGE_TYPE=mem

    zookeeper:
      image: wurstmeister/zookeeper:latest
      ports:
        - "2181:2181"
      volumes:
        - zookeeper_data:/data
        - zookeeper_datalog:/datalog
      networks:
        - broadcom-network
      healthcheck:
        test: [ "CMD", "sh", "-c", "echo ruok | nc localhost 2181 | grep imok" ]
        interval: 30s
        timeout: 10s
        retries: 5

    kafka:
      image: wurstmeister/kafka:latest
      ports:
        - "9092:9092"
      depends_on:
        - zookeeper
      expose:
        - "9093"
      environment:
        KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
        KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
        KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_CREATE_TOPICS: "my-topic:1:1"
        KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
        KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      networks:
        - broadcom-network
      healthcheck:
        test: [ "CMD", "kafka-topics.sh", "--list", "--zookeeper", "zookeeper:2181" ]
        interval: 10s
        timeout: 5s
        retries: 5

    mysqldb:
      image: mysql:8.0
      container_name: mysql-container
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: admin
        MYSQL_DATABASE: authentication
      ports:
        - "3307:3306"
      volumes:
        - mysql-data:/var/lib/mysql
      networks:
        - broadcom-network
      healthcheck:
        test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
        interval: 10s
        timeout: 5s
        retries: 3

    namingserver:
      image: broadcom-namingserver:1.1.1
      restart: always
      ports:
        - "7000:7000"
      depends_on:
        mysqldb:
          condition: service_healthy
        zipkin:
          condition: service_healthy
      networks:
          - broadcom-network
      environment:
          - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411
      healthcheck:
         test: [ "CMD", "curl", "-f", "http://localhost:7100/actuator/health" ]
         interval: 30s
         timeout: 10s
         retries: 5

    apigateway:
      image: broadcom-apigateway:2.1.1
      restart: always
      ports:
        - "7100:7100"
      depends_on:
        namingserver:
          condition: service_healthy
        kafka:
          condition: service_healthy
        mysqldb:
          condition: service_healthy
        zipkin:
          condition: service_healthy
        networks:
          - broadcom-network
      environment:
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://namingserver:7000/eureka/
        - AUTHENTICATION_SERVICE_URL=http://authentication:7200
        - BROADCOMAPP_SERVICEURL=http://broadcomapp:7210
        - BROADCOM_COMMUNICATION_TOKEN=ABCD_1234
        - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411
      healthcheck:
         test: [ "CMD", "curl", "-f", "http://localhost:7000/actuator/health" ]
         interval: 30s
         timeout: 10s
         retries: 5

    authentication:
      image: broadcom-authentication:3.1.1
      restart: always
      ports:
        - "7200:7200"
      depends_on:
        apigateway:
          condition: service_healthy
        namingserver:
          condition: service_healthy
        kafka:
          condition: service_healthy
        mysqldb:
          condition: service_healthy
        zipkin:
          condition: service_healthy
        networks:
          - broadcom-network
      environment:
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://namingserver:7000/eureka/
        - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/authentication?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
        - SPRING_DATASOURCE_USERNAME=root
        - SPRING_DATASOURCE_PASSWORD=admin
        - BROADCOM_COMMUNICATION_TOKEN=ABCD_1234
        - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411
      healthcheck:
         test: [ "CMD", "curl", "-f", "-H", "broadcom_communication_token:ABCD_1234", "http://localhost:7200/actuator/health" ]
         interval: 30s
         timeout: 10s
         retries: 5

    broadcomapp:
      image: broadcom-broadcomapp:4.1.1
      restart: always
      ports:
        - "7210:7210"
      depends_on:
        apigateway:
          condition: service_healthy
        namingserver:
          condition: service_healthy
        authentication:
          condition: service_healthy
        kafka:
          condition: service_healthy
        mysqldb:
          condition: service_healthy
        zipkin:
          condition: service_healthy
        networks:
          - broadcom-network
      environment:
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://namingserver:7000/eureka/
        - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/broadcomapp?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
        - SPRING_DATASOURCE_USERNAME=root
        - SPRING_DATASOURCE_PASSWORD=admin
        - BROADCOM_COMMUNICATION_TOKEN=ABCD_1234
        - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9093
        - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411
      healthcheck:
          test: [ "CMD", "curl", "-f","-H", "broadcom_communication_token:ABCD_1234", "http://localhost:7100/actuator/health" ]
          interval: 30s
          timeout: 10s
          retries: 5

    broadcomaui:
      image: broadcom-broadcomaui:7.1.1
      restart: always
      ports:
        - "7214:7214"
      depends_on:
        apigateway:
          condition: service_healthy
        namingserver:
          condition: service_healthy
        authentication:
          condition: service_healthy
        broadcomapp:
          condition: service_healthy
        kafka:
          condition: service_healthy
        mysqldb:
          condition: service_healthy
      networks:
        - broadcom-network
      healthcheck:
        test: [ "CMD", "curl", "-f", "http://localhost:7214" ]
        interval: 30s
        timeout: 10s
        retries: 5

    emailsender:
      image: broadcom-emailsender:8.1.1
      restart: always
      ports:
        - "7230:7230"
      depends_on:
        kafka:
          condition: service_healthy
        mysqldb:
          condition: service_healthy
        zipkin:
          condition: service_healthy
      networks:
          - broadcom-network
      environment:
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://namingserver:7000/eureka/
        - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/emailsender?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
        - SPRING_DATASOURCE_USERNAME=root
        - SPRING_DATASOURCE_PASSWORD=admin
        - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9093
        - SPRING_KAFKA_BOOTSTRAP_GROUP_ID=broadcom-group
        - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411
      healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:7230/actuator/health" ]
            interval: 30s
            timeout: 10s
            retries: 5

    smssender:
      image: broadcom-smssender:9.1.1
      restart: always
      ports:
        - "7231:7231"
      depends_on:
        kafka:
          condition: service_healthy
        mysqldb:
          condition: service_healthy
        zipkin:
          condition: service_healthy
      networks:
        - broadcom-network
      environment:
        - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://namingserver:7000/eureka/
        - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/smssender?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
        - SPRING_DATASOURCE_USERNAME=root
        - SPRING_DATASOURCE_PASSWORD=admin
        - SPRING_KAFKA_BOOTSTRAP_SERVERS=kafka:9093
        - SPRING_KAFKA_BOOTSTRAP_GROUP_ID=broadcom-group
        - SPRING_ZIPKIN_BASE-URL=http://zipkin:9411
      healthcheck:
          test: [ "CMD", "curl", "-f", "http://localhost:7231/actuator/health" ]
          interval: 30s
          timeout: 10s
          retries: 5

networks:
  broadcom-network:
    driver: bridge

volumes:
  zookeeper_data:
  zookeeper_datalog:
  kafka_data:
  mysql-data:
