version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"
    volumes:
      - zookeeper_data:/data
      - zookeeper_datalog:/datalog
    networks:
      - broadcom-network

  kafka:
      image: wurstmeister/kafka:2.12-2.1.1
      ports:
        - "9092:9092"
      environment:
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      volumes:
        - kafka_data:/kafka
      networks:
        - broadcom-network

  namingserver:
    image: broadcom-namingserver:1.1.1
    restart: always
    ports:
      - "7100:7100"
    networks:
      - broadcom-network

  apigateway:
    image: broadcom-apigateway:2.1.1
    restart: always
    ports:
      - "7000:7000"
    depends_on:
      - namingserver
    networks:
      - broadcom-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://namingserver:7100/eureka/
      - AUTHENTICATION_SERVICEURL=http://localhost:7200

  authentication:
    image: broadcom-authentication:3.1.1
    restart: always
    ports:
      - "7200:7200"
    depends_on:
      - apigateway
    networks:
      - broadcom-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://namingserver:7100/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/authentication?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=admin

  broadcomapp:
    image: broadcom-broadcomapp:4.1.1
    restart: always
    ports:
      - "7210:7210"
    depends_on:
      - authentication
    networks:
      - broadcom-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://namingserver:7100/eureka/
      - SPRING_DATASOURCE_URL=jdbc:mysql://host.docker.internal:3306/broadcomapp?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=admin

  broadcomaui:
    image: broadcom-broadcomaui:7.1.1
    restart: always
    ports:
      - "7214:7214"
    depends_on:
      - authentication
      - namingserver
      - apigateway
    networks:
      - broadcom-network

networks:
  broadcom-network:
    driver: bridge

volumes:
  zookeeper_data:
  zookeeper_datalog:
  kafka_data: