spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: http://localhost:3000,http://localhost:7100,http://localhost:7214
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true